### ISSUE TITLE
[ERROR] Not working

### ISSUE THREAD

**Issue by alphanumericaltycoon** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#101]
**Describe the error**
Script launches chrome webpage which goes to https://vipto.de/ which then presents 502 bad gateway page.

Terminal shows errors:

```
┌──(kali㉿kali)-[~/TikTok-Follow-Heart-Views-Bot]
└─$ python3 Bot.py                                                                                                                                         1 ⨯
Author: https://github.com/NoNameoN-A
What do you want to do?
1 - Auto views(500)
2 - Auto hearts
3 - Auto (FIRST) comments heart
4 - Auto followers
5 - Auto Share
6 - Simple reload
1
/home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py:161: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=r'/home/kali/TikTok-Follow-Heart-Views-Bot/chromedriver',chrome_options=chrome_options) #Change it
/home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py:161: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=r'/home/kali/TikTok-Follow-Heart-Views-Bot/chromedriver',chrome_options=chrome_options) #Change it
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
Traceback (most recent call last):
  File "/home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py", line 11, in loop1
    driver.find_element_by_xpath("//*[@id=\"main\"]/div/div[4]/div/button").click()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 399, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 1012, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="main"]/div/div[4]/div/button"}
  (Session info: chrome=92.0.4515.107)

```

If I try another option from the menu it's still the same issue with the webpage. Terminal shows:

                                                                                                                                                               
```
┌──(kali㉿kali)-[~/TikTok-Follow-Heart-Views-Bot]
└─$ python3 Bot.py                                                                                                                                         1 ⨯
Author: https://github.com/NoNameoN-A
What do you want to do?
1 - Auto views(500)
2 - Auto hearts
3 - Auto (FIRST) comments heart
4 - Auto followers
5 - Auto Share
6 - Simple reload
2
/home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py:161: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=r'/home/kali/TikTok-Follow-Heart-Views-Bot/chromedriver',chrome_options=chrome_options) #Change it
/home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py:161: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=r'/home/kali/TikTok-Follow-Heart-Views-Bot/chromedriver',chrome_options=chrome_options) #Change it
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.
You didn't solve the captcha yet. Need to refresh to avoid endless loop.

```

**Info**

Chrome Version 92.0.4515.107 (Official Build) (64-bit)
Chrome Driver: ChromeDriver 92.0.4515.107   (http://chromedriver_linux64.zip/)
OS: Kali Linux-2021.2

**Comment by rin1906** [comment]
> **Describe the error**
> Script launches chrome webpage which goes to https://vipto.de/ which then presents 502 bad gateway page.
> 
> Terminal shows errors:
> 
> ```
> ┌──(kali㉿kali)-[~/TikTok-Follow-Heart-Views-Bot]
> └─$ python3 Bot.py                                                                                                                                         1 ⨯
> Author: https://github.com/NoNameoN-A
> What do you want to do?
> 1 - Auto views(500)
> 2 - Auto hearts
> 3 - Auto (FIRST) comments heart
> 4 - Auto followers
> 5 - Auto Share
> 6 - Simple reload
> 1
> /home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py:161: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
>   driver = webdriver.Chrome(executable_path=r'/home/kali/TikTok-Follow-Heart-Views-Bot/chromedriver',chrome_options=chrome_options) #Change it
> /home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py:161: DeprecationWarning: use options instead of chrome_options
>   driver = webdriver.Chrome(executable_path=r'/home/kali/TikTok-Follow-Heart-Views-Bot/chromedriver',chrome_options=chrome_options) #Change it
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> Traceback (most recent call last):
>   File "/home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py", line 11, in loop1
>     driver.find_element_by_xpath("//*[@id=\"main\"]/div/div[4]/div/button").click()
>   File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 399, in find_element_by_xpath
>     return self.find_element(by=By.XPATH, value=xpath)
>   File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 1012, in find_element
>     return self.execute(Command.FIND_ELEMENT, {
>   File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
>     self.error_handler.check_response(response)
>   File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="main"]/div/div[4]/div/button"}
>   (Session info: chrome=92.0.4515.107)
> ```
> 
> If I try another option from the menu it's still the same issue with the webpage. Terminal shows:
> 
> ```
> ┌──(kali㉿kali)-[~/TikTok-Follow-Heart-Views-Bot]
> └─$ python3 Bot.py                                                                                                                                         1 ⨯
> Author: https://github.com/NoNameoN-A
> What do you want to do?
> 1 - Auto views(500)
> 2 - Auto hearts
> 3 - Auto (FIRST) comments heart
> 4 - Auto followers
> 5 - Auto Share
> 6 - Simple reload
> 2
> /home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py:161: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
>   driver = webdriver.Chrome(executable_path=r'/home/kali/TikTok-Follow-Heart-Views-Bot/chromedriver',chrome_options=chrome_options) #Change it
> /home/kali/TikTok-Follow-Heart-Views-Bot/Bot.py:161: DeprecationWarning: use options instead of chrome_options
>   driver = webdriver.Chrome(executable_path=r'/home/kali/TikTok-Follow-Heart-Views-Bot/chromedriver',chrome_options=chrome_options) #Change it
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> You didn't solve the captcha yet. Need to refresh to avoid endless loop.
> ```
> 
> **Info**
> 
> Chrome Version 92.0.4515.107 (Official Build) (64-bit)
> Chrome Driver: ChromeDriver 92.0.4515.107 (http://chromedriver_linux64.zip/)
> OS: Kali Linux-2021.2

Hi.  Can you guide me how to put it on the domain name?

**Comment by mijandro669** [comment]
Same happens to me.
