### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by GGNosen** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#104]
Traceback (most recent call last):
  File "tiktok.py", line 2, in <module>
    from selenium import webdriver
ImportError: No module named selenium

**Comment by GGNosen** [comment]
i need help

**Comment by GGNosen** [comment]
Bot.py:161: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=r'',chrome_options=chrome_options) #Change it
Traceback (most recent call last):
  File "/home/ggnosen/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Bot.py", line 161, in <module>
    driver = webdriver.Chrome(executable_path=r'',chrome_options=chrome_options) #Change it
  File "/home/ggnosen/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/ggnosen/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: '' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by GGNosen** [comment]
what is that

**Comment by JulianSobott** [comment]
Two options. Either you have some weird configs, which cause the permission denied exception or the script is outdated. I haven't tested the script myself yet. I think you could rewrite it and use modern selenium config. https://selenium-python.readthedocs.io/

Maybe I can try it myself later on.
