### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ubed354311** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#16]
Traceback (most recent call last):
  File "TikTok-Views-Follow-Heart-Bot.py", line 14, in <module>
    driver = webdriver.Chrome('/your/path/for/chromedriver',chrome_options=chrome_options) #If you use Windows you must add .exe
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by ubed354311** [comment]
Traceback (most recent call last):
  File "TikTok-Views-Follow-Heart-Bot.py", line 14, in <module>
    driver = webdriver.Chrome('/your/path/for/chromedriver',chrome_options=chrome_options) #If you use Windows you must add .exe
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by NoNameoN-A** [comment]
`webdriver.Chrome('/your/path/for/chromedriver',chrome_options=chrome_options) #If you use Windows you must add .exe `

Change with your chromedriver path

**Comment by ubed354311** [comment]
i must used python2 or python3????
and i dont understand if you see windows you must add .exe

driver = webdriver.Chrome('/your/path/for/chromedriver',chrome_options=chrome_options) #If you use Windows you must add .exe
Traceback (most recent call last):
  File "C:\python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Asus\Downloads\TikTok-Follow-Heart-Views-Bot-main\TikTok-Follow-Heart-Views-Bot-main\tt.py", line 14, in <module>
    driver = webdriver.Chrome('/your/path/for/chromedriver',chrome_options=chrome_options) #If you use Windows you must add .exe
  File "C:\python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by NoNameoN-A** [comment]
[Start the bot with python TikTok-Views-Follow-Heart-Bot.py and insert the Captcha.](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#start)

and

`webdriver.Chrome('/your/path/for/chromedriver',chrome_options=chrome_options) #If you use Windows you must add .exe`
Change with your chromedriver path
[Line link](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/blob/ab43bd24e84286c52a9f8c2ec34775c2d701ca58/TikTok-Views-Follow-Heart-Bot.py#L14)
