### ISSUE TITLE
Issue when pressing 1, 2, 3 or 4, program crashes

### ISSUE THREAD

**Issue by ImOnlyHereForCSGOHacks** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#33]
Error is 
Warning (from warnings module):
  File "C:\Users\User1\Desktop\TikTok-Follow-Heart-Views-Bot-Release\Bot_For_Bugged.py", line 139
    driver = webdriver.Chrome('C:/Users/User1/Desktop/TikTok-Follow-Heart-Views-Bot-main/chromedriver.exe',chrome_options=chrome_options)
DeprecationWarning: use options instead of chrome_options
Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User1\Desktop\TikTok-Follow-Heart-Views-Bot-Release\Bot_For_Bugged.py", line 139, in <module>
    driver = webdriver.Chrome('C:/Users/User1/Desktop/TikTok-Follow-Heart-Views-Bot-main/chromedriver.exe',chrome_options=chrome_options)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by NoNameoN-A** [comment]
Hi try inserting chromedriver.exe on the bot folder or in the path... however if you want i can give you a video tutorial privatly if follow me on gthub and release a star on the repository :)

**Comment by Gam3rBoy57** [comment]
I have the same problem. Could someone help me please?

**Comment by NoNameoN-A** [comment]
@Gam3rBoy57 send a photo

**Comment by Gam3rBoy57** [comment]
![image](https://user-images.githubusercontent.com/63651360/105396077-c09a2080-5c1f-11eb-90b6-7aa1235ca66a.png)
@NoNameoN-A

**Comment by NoNameoN-A** [comment]
the problem is with your chromedriver
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work.
