### ISSUE TITLE
[BUG] ChromeDriver Problem

### ISSUE THREAD

**Issue by jokerjokerjokerjokerjoker** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#40]
Did everything like the description says

The Error:
Bot_For_Bugged.py:139: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome('/usr/bin/chromedriver',chrome_options=chrome_options) #Change it
Traceback (most recent call last):
  File "Bot_For_Bugged.py", line 139, in <module>
    driver = webdriver.Chrome('/usr/bin/chromedriver',chrome_options=chrome_options) #Change i                                             t
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 7                                             6, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 1                                             57, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 2                                             52, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 3                                             21, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", lin                                             e 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start:                                              exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so                                              ChromeDriver is assuming that Chrome has crashed.)

**Comment by NoNameoN-A** [comment]
# VIDEO FOR BEGINNERS - Windows aviable
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work

[Email](mailto:alessandrogreco@hacari.org)
[Repository](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#video-for-beginners---windows-aviable)

**Comment by jokerjokerjokerjokerjoker** [comment]
I'm using a linux server, not a windows server.

**Comment by NoNameoN-A** [comment]
Hi the problem can come from selenium, we have detected a bug.
However try using Bot.py , then sy us if you have solved or not :)

**Comment by NoNameoN-A** [comment]
The problem come from chromedriver, if you want try to solve send me an email for tutorial video
