### ISSUE TITLE
[ERROR]executable code?

### ISSUE THREAD

**Issue by Icarus1337** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#55]
bot.py:139: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=r'Users/jafar/OneDrive/Documents/codingstuf/TikTok-Follow-Heart-Views-Bot-main/chromedriver.exe',chrome_options=chrome_options) #Change it
Traceback (most recent call last):
  File "C:\Users\jafar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 139, in <module>
    driver = webdriver.Chrome(executable_path=r'Users/jafar/OneDrive/Documents/codingstuf/TikTok-Follow-Heart-Views-Bot-main',chrome_options=chrome_options) #Change it
  File "C:\Users\jafar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\jafar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'TikTok-Follow-Heart-Views-Bot-main' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

this is  my error rn

**Comment by Icarus1337** [comment]
fixed
