### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by GokBoruEfe** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#64]
`Bot.py:139: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=r'//home/n5k5i5/Masaüstü/chromedriver',chrome_options=chrome_options) #Change it
Bot.py:139: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=r'//home/n5k5i5/Masaüstü/chromedriver',chrome_options=chrome_options) #Change it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '//home/n5k5i5/Masaüstü/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Bot.py", line 139, in <module>
    driver = webdriver.Chrome(executable_path=r'//home/n5k5i5/Masaüstü/chromedriver',chrome_options=chrome_options) #Change it
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

`

**Comment by NoNameoN-A** [comment]
try with this path `/home/n5k5i5/Masaüstü/chromedriver` however try to insert your chromedriver in bot directory
