### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by Lukegod2000** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#83]
Hello
Got this path error
Traceback (most recent call last):
  File "C:\Users\lukeg\Downloads\TikTok-Follow-Heart-Views-Bot-main (1)\TikTok-Follow-Heart-Views-Bot-main\Bot.py", line 161, in <module>
    driver = webdriver.Chrome(executable_path=r'\Users\lukeg\Downloads\chromedriver_win32 (2)',chrome_options=chrome_options) #Change it
  File "C:\Users\lukeg\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\lukeg\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_win32 (2)' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by Lucas559-noob** [comment]
you need to put the chrome driver idk where, and in py you open it with a text editor(I recommend notepad++) and in that line 161 change the path of` webdriver.Chrome(executable_path=r'\Users\lukeg\Downloads\chromedriver_win32 (2)',chrome_options=chrome_options)` to r'\Users\Pog\Windows' idk where it is
