### ISSUE TITLE
[ERROR] How can i fix this?

### ISSUE THREAD

**Issue by Njemac** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#89]
###  **How can i fix this?**
_______________________________________________
![Screenshot_2021-06-22-13-33-22](https://user-images.githubusercontent.com/67206114/122918577-90d27e80-d35f-11eb-8d71-e97e24324f6f.png)
________________________________________________ 
`/data/data/com.termux/files/home/tiktok/bot.py:161: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=r'/tiktok/chromedriver',chrome_options=chrome_options) #Change it
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tiktok/chromedriver'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/tiktok/bot.py", line 161, in <module>                           driver = webdriver.Chrome(executable_path=r'/tiktok/chromedriver',chrome_options=chrome_options) #Change it
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home `

**Comment by NoNameoN-A** [comment]
you need a computer
